### ISSUE TITLE
Attributes when calling `_set_desired_longitude_range`

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#1137]
Longitude attributes are lost when calling this function.

**Comment by erogluorhan** [comment]
@philipc2 check if this is already fixed

**Comment by philipc2** [comment]
> [@philipc2](https://github.com/philipc2) check if this is already fixed

Looks like the attributes still get clobbered. I've moved this up and changed it to To-do
